[tool.poetry]
name = "mercury"
version = "0.1.0"
description = ""
authors = ["Nicholas Romero <ncrmro@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
